# Site settings
title: ZXL Blog
SEOTitle: ZXLçš„åšå®¢ | ZXL Blog
header-img: img/post-bg-desk.jpg
email: ZXL2024903531@outlook.com
description: "Hiï¼Œæˆ‘æ˜¯SCAUçš„æŸä½è½¯ä»¶å·¥ç¨‹å¤§å­¦ç”Ÿï¼Œå¸Œæœ›å’Œå¤§å®¶åˆ†äº«æˆ‘çš„ä¸ªäººçŸ¥è¯†æ€»ç»“ï¼"
keyword: "ZXL, ZXL Blog, ZXLyyds100, éƒ‘é‘«äº®, Java, Spring, SpringBoot, SpringCloud, MySQL, Redis, è½¯ä»¶å·¥ç¨‹"
url: "https://ZXLyyds100.github.io"
baseurl: ""
github_repo: "https://github.com/ZXLyyds100/ZXLyyds100.github.io"

# Sidebar settings
sidebar: true
sidebar-about-description: "Goals determine what you going to be! ğŸš€ åˆ†äº«æŠ€æœ¯ï¼Œè®°å½•æˆé•¿"
sidebar-avatar: /img/about-BY-gentle.jpg

# SNS settings
RSS: false
github_username: ZXLyyds100
# weibo_username: 
# zhihu_username: 
# facebook_username: 
# jianshu_username: 
# twitter_username: 

# Build settings
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true

# Gems
gems: [jekyll-paginate]

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# è¯„è®ºç³»ç»Ÿ
# Disqus
# disqus_username: 

# Gitalk
gitalk:
  enable: true
  clientID: f2c84e7629bb1446c1a4
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d
  repo: ZXLyyds100.github.io
  owner: ZXLyyds100
  admin: ZXLyyds100
  distractionFreeMode: true

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'
ga_domain: auto

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "GitHub",
        href: "https://github.com/ZXLyyds100"
    },{
        title: "Springå®˜ç½‘",
        href: "https://spring.io"
    },{
        title: "Javaå®˜ç½‘",
        href: "https://www.oracle.com/java/"
    },{
        title: "åå—å†œä¸šå¤§å­¦",
        href: "https://www.scau.edu.cn"
    }
]
